### ISSUE TITLE
Issues with i3 shortcuts

### ISSUE THREAD

**Issue by landorg** [yusufaktepe/rofi-gpaste#2]
Hi
I'm having problems to run this from an i3 shortcut. While it works fine from the command line it hangs from the shortcut
```
bindsym --release $alt+ctrl+h exec "/bin/rofi-gpaste --debug &> /tmp/out"
```
/tmp/out 
```
+ export SHELLOPTS
+ exec /bin/rofi-gpaste
+ Kb_Clear=Alt+c
+ Kb_Toggle=Alt+p
+ Kb_Delete=Alt+d
+ Kb_Edit=Alt+e
+ Kb_Archive=Alt+s
+ Kb_Hist=Alt+h
+ Kb_Paste=Alt+Return
+ Kb_QR=Alt+q
+ Kb_Save=Alt+o
+ Kb_Backup=Alt+B
+ Kb_Switch_Main=Alt+1
+ Kb_Switch_Archive=Alt+2
+ Kb_LaunchGUI=F1
+ Editor=xdg-open
+ ImageViewer=xdg-open
+ PromptPrefix=' '
+ ConfigFile=/home/roland/.config/rofi-gpaste.conf
+ '[' -f /home/roland/.config/rofi-gpaste.conf ']'
+ Script=rofi-gpaste
+ GpasteDir=/home/roland/.local/share/gpaste
+ pidof -q gpaste-daemon
+ case $1 in
+ menu
++ gpaste-client get-history
```

It always hangs on the `gpaste-client get-history` command. Also directly using that command makes it hang:
```
❯ pgrep -a gpaste
34408 /usr/lib/gpaste/gpaste-daemon
72155 /bin/bash /bin/rofi-gpaste
72158 gpaste-client get-history
```

Any idea what might be missing there?

**Comment by yusufaktepe** [comment]
Could you reset gpaste and try again?

Run:
```shell
pkill -f gpaste
dconf reset -f /org/gnome/GPaste/
mv ~/.local/share/gpaste ~/.local/share/gpaste.old
```

**Comment by landorg** [comment]
It's exactly the same.
After the reset:
```
❯ pkill -f gpaste


❯ dconf reset -f /org/gnome/GPaste/


❯ mv ~/.local/share/gpaste ~/.local/share/gpaste.old


❯ pgrep -a gpaste

(I hit the shortcut)

❯ cat /tmp/out
+ export SHELLOPTS
+ exec /bin/rofi-gpaste
+ Kb_Clear=Alt+c
+ Kb_Toggle=Alt+p
+ Kb_Delete=Alt+d
+ Kb_Edit=Alt+e
+ Kb_Archive=Alt+s
+ Kb_Hist=Alt+h
+ Kb_Paste=Alt+Return
+ Kb_QR=Alt+q
+ Kb_Save=Alt+o
+ Kb_Backup=Alt+B
+ Kb_Switch_Main=Alt+1
+ Kb_Switch_Archive=Alt+2
+ Kb_LaunchGUI=F1
+ Editor=xdg-open
+ ImageViewer=xdg-open
+ PromptPrefix=' '
+ ConfigFile=/home/roland/.config/rofi-gpaste.conf
+ '[' -f /home/roland/.config/rofi-gpaste.conf ']'
+ Script=rofi-gpaste
+ GpasteDir=/home/roland/.local/share/gpaste
+ pidof -q gpaste-daemon
+ setsid -f gpaste-client daemon
+ case $1 in
+ menu
++ gpaste-client get-history

❯ pgrep -a gpaste
1090965 /bin/bash /bin/rofi-gpaste
1090968 gpaste-client daemon
1090973 /usr/lib/gpaste/gpaste-daemon
1090975 gpaste-client daemon
1090976 gpaste-client get-history
```

Starting it from the terminal still works

**Comment by yusufaktepe** [comment]
> hangs on the gpaste-client get-history command. Also directly using that command makes it hang
> While it works fine from the command line it hangs from the shortcut

It's strange that the `gpaste-client get-history` command hangs when executed from i3 or outside the script, while it doesn't hang when the script is initiated from the terminal. I can't think of a reason for this behavior.

I suggest creating an issue at the GPaste repo since there seems to be an issue with the `gpaste-client get-history` command.

**Comment by landorg** [comment]
My guess it's missing some environment variables to work properly that are not there on i3 level. What does that client use to connect to gpaste?

**Comment by yusufaktepe** [comment]
> My guess it's missing some environment variables to work properly that are not there on i3 level. What does that client use to connect to gpaste?

I'm not sure.

If the only issue is with the `get-history` command, we can workaround that. Can you try [dconf-get-history](https://github.com/yusufaktepe/rofi-gpaste/tree/dconf-get-history) branch to check if it works?

**Comment by landorg** [comment]
Hi.
Sorry for the delay. 
Yes from that branch i get the rofi menu and it works

**Comment by landorg** [comment]
Ah sorry that was wrong.
When I have gpaste running next thing that hangs is:
```
gpaste-client --oneline
```

**Comment by yusufaktepe** [comment]
> Ah sorry that was wrong. When I have gpaste running next thing that hangs is:
> 
> ```
> gpaste-client --oneline
> ```

In that case, there is something wrong with your installation or environment. You should open an issue at [gpaste repo](https://github.com/Keruspe/GPaste) for that.
